/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1B5dPzeajw3
 */

export function AccordionQuestions() {
  return (
    <div className="max-w-2xl mx-auto my-16">
      <h2 className="text-2xl font-semibold mb-4">
        Frequently Asked Questions
      </h2>
      <div className="space-y-4">
        <details className="p-4 border rounded-lg">
          <summary className="text-lg font-medium cursor-pointer">
            How do I get started?
          </summary>
          <p className="pt-2 text-gray-600">
            To start using Texty, simply upload your text file and choose the
            format you want to convert it to. We support PNG, JPG, SVG, and PDF.
            Plus, you can convert PDFs to HTML elements effortlessly.
          </p>
        </details>
        <details className="p-4 border rounded-lg">
          <summary className="text-lg font-medium cursor-pointer">
            Is there a paid account?
          </summary>
          <p className="pt-2 text-gray-600">
            No, there is no paid account. Everything is free and open sourced.
          </p>
        </details>
        <details className="p-4 border rounded-lg">
          <summary className="text-lg font-medium cursor-pointer">
            Can I convert files in bulk?
          </summary>
          <p className="pt-2 text-gray-600">
            Yes, Texty offers bulk conversion capabilities, making it easy to
            convert multiple files at once, saving you time and effort.
          </p>
        </details>
      </div>
      <div className="text-center mt-6">
        <p className="text-gray-600">
          Can't find what you're looking for?
          <a className="text-blue-600 hover:underline" href="#">
            Contact our support
          </a>
        </p>
      </div>
    </div>
  );
}
