/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6Q7ipvRT6FP
 */
import { Button } from "@/components/ui/button"

export function PageLinkSection() {
  return (
    <div className="flex justify-between">
      <div className="text-center">
        <div className="mx-auto mb-4 h-16 w-16 rounded-full bg-blue-200">
          <ShieldIcon className="text-blue-600" />
        </div>
        <h3 className="mb-2 text-lg font-semibold">PNG Conversion</h3>
        <p className="text-gray-600">Convert your files to PNG format with just a single click.</p>
        <Button className="mt-4" variant="secondary">
          Convert to PNG
        </Button>
      </div>
      <div className="text-center">
        <div className="mx-auto mb-4 h-16 w-16 rounded-full bg-yellow-200">
          <RocketIcon className="text-yellow-600" />
        </div>
        <h3 className="mb-2 text-lg font-semibold">JPG Conversion</h3>
        <p className="text-gray-600">Get your files in JPG format with our super-fast conversion tool.</p>
        <Button className="mt-4" variant="secondary">
          Convert to JPG
        </Button>
      </div>
      <div className="text-center">
        <div className="mx-auto mb-4 h-16 w-16 rounded-full bg-green-200">
          <MoonStarIcon className="text-green-600" />
        </div>
        <h3 className="mb-2 text-lg font-semibold">SVG Conversion</h3>
        <p className="text-gray-600">Choose SVG format for scalable vector graphics conversion.</p>
        <Button className="mt-4" variant="secondary">
          Convert to SVG
        </Button>
      </div>
      <div className="text-center">
        <div className="mx-auto mb-4 h-16 w-16 rounded-full bg-pink-200">
          <MicroscopeIcon className="text-pink-600" />
        </div>
        <h3 className="mb-2 text-lg font-semibold">PDF to HTML Conversion</h3>
        <p className="text-gray-600">Convert your PDF files to HTML format with our easy-to-use converter.</p>
        <Button className="mt-4" variant="secondary">
          Convert PDF to HTML
        </Button>
      </div>
    </div>
  )
}


function ShieldIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10" />
    </svg>
  )
}


function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}


function MoonStarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
      <path d="M19 3v4" />
      <path d="M21 5h-4" />
    </svg>
  )
}


function MicroscopeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>
  )
}
